/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Guis;

import Modelos.buses;
import javax.swing.JOptionPane;

/**
 *
 * @author JhonLegends
 */
public class BusGui extends javax.swing.JFrame {

    /**
     * Creates new form BusGui
     */
    public BusGui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btGroupSoat = new javax.swing.ButtonGroup();
        btGroupTecno = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnRegistrarBus = new javax.swing.JButton();
        txtPlaca = new javax.swing.JTextField();
        txtTipoBus = new javax.swing.JTextField();
        txtCantidadSillas = new javax.swing.JTextField();
        radioSoatSi = new javax.swing.JRadioButton();
        radioSoatNo = new javax.swing.JRadioButton();
        radioTecnoNo = new javax.swing.JRadioButton();
        radioTecnoSi = new javax.swing.JRadioButton();
        btnAtras = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("REGISTRAR BUS");

        jLabel2.setText("PLACA:");

        jLabel3.setText("TIPO BUS:");

        jLabel4.setText("SILLAS DISPONIBLES:");

        jLabel5.setText("SOAT:");

        jLabel6.setText("TECNOMECANICA:");

        btnRegistrarBus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save.png"))); // NOI18N
        btnRegistrarBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarBusActionPerformed(evt);
            }
        });

        btGroupSoat.add(radioSoatSi);
        radioSoatSi.setText("Si");
        radioSoatSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSoatSiActionPerformed(evt);
            }
        });

        btGroupSoat.add(radioSoatNo);
        radioSoatNo.setText("No");
        radioSoatNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSoatNoActionPerformed(evt);
            }
        });

        btGroupTecno.add(radioTecnoNo);
        radioTecnoNo.setText("No");
        radioTecnoNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioTecnoNoActionPerformed(evt);
            }
        });

        btGroupTecno.add(radioTecnoSi);
        radioTecnoSi.setText("Si");
        radioTecnoSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioTecnoSiActionPerformed(evt);
            }
        });

        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/return.png"))); // NOI18N
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnRegistrarBus)
                        .addComponent(jLabel6)))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPlaca)
                    .addComponent(txtCantidadSillas)
                    .addComponent(txtTipoBus)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(radioTecnoSi)
                                    .addComponent(radioSoatSi)))
                            .addComponent(btnAtras))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(radioSoatNo)
                                    .addComponent(radioTecnoNo)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(btnBuscar)))))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(63, 63, 63))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtTipoBus, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCantidadSillas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(radioSoatSi)
                    .addComponent(radioSoatNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(radioTecnoSi)
                    .addComponent(radioTecnoNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnRegistrarBus)
                        .addComponent(btnAtras))
                    .addComponent(btnBuscar))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarBusActionPerformed
        String placa = txtPlaca.getText();
        String tipoBus = txtTipoBus.getText();
        int cantidadSillas = Integer.valueOf(txtCantidadSillas.getText());
        boolean soat= false;
        if (radioSoatSi.isSelected()) {
            soat = true;
        } else if (radioSoatNo.isSelected()) {
            soat = false;
        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar el estado del soat");
        }
        boolean tecnomecanica= false;
        if (radioTecnoSi.isSelected()) {
            tecnomecanica = true;
        } else if (radioTecnoNo.isSelected()) {
            tecnomecanica = false;
        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar el estado del soat");
        }
        buses objBuses= new buses(placa, tipoBus, cantidadSillas, soat, tecnomecanica);
        objBuses.setObjBuses(objBuses);
        objBuses.recorrerBuses();
        JOptionPane.showMessageDialog(this, "REGISTRO EXITOSO");
        Limpiar();
    }//GEN-LAST:event_btnRegistrarBusActionPerformed

    private void radioSoatSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSoatSiActionPerformed

        if (radioSoatSi.isSelected()) {
            radioSoatNo.setSelected(false);
        }
    }//GEN-LAST:event_radioSoatSiActionPerformed

    private void radioSoatNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSoatNoActionPerformed

        if (radioSoatNo.isSelected()) {
            radioSoatSi.setSelected(false);
        }
    }//GEN-LAST:event_radioSoatNoActionPerformed

    private void radioTecnoNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioTecnoNoActionPerformed
        // TODO add your handling code here:
        if (radioTecnoNo.isSelected()) {
            radioTecnoSi.setSelected(false);
        }
    }//GEN-LAST:event_radioTecnoNoActionPerformed

    private void radioTecnoSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioTecnoSiActionPerformed
        // TODO add your handling code here:
        if (radioTecnoSi.isSelected()) {
            radioTecnoNo.setSelected(false);
        }
    }//GEN-LAST:event_radioTecnoSiActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        Registros btnAtras = new Registros();
        btnAtras.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String placa = JOptionPane.showInputDialog(this, "Ingrese el NIT");
        buses objBuses2 = new buses();
        buses buscaBus[] = objBuses2.getObjBuses();
        for (int i = 0; i < buscaBus.length; i++) {
            if (buscaBus[i].getPlaca().equals(placa)) {
                txtPlaca.setText(buscaBus[i].getPlaca());
                txtCantidadSillas.setText(Integer.toString(buscaBus[i].getCantidadSillas()));
                txtTipoBus.setText(buscaBus[i].getTipoBus());
                if(buscaBus[i].isSoat()){
                   radioSoatSi.setSelected(true);
                }else if(!(buscaBus[i].isSoat())){
                    radioSoatNo.setSelected(true);
                }
                if(buscaBus[i].isTecnomecanica()){
                   radioTecnoSi.setSelected(true);
                }else if(!(buscaBus[i].isTecnomecanica())){
                    radioTecnoNo.setSelected(true);
                }
                break;
            }
        }
    }//GEN-LAST:event_btnBuscarActionPerformed
    public void Limpiar(){
        txtCantidadSillas.setText("");
        txtPlaca.setText("");
        txtTipoBus.setText("");
        btGroupSoat.clearSelection();
        btGroupTecno.clearSelection();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BusGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BusGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BusGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BusGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BusGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btGroupSoat;
    private javax.swing.ButtonGroup btGroupTecno;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnRegistrarBus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton radioSoatNo;
    private javax.swing.JRadioButton radioSoatSi;
    private javax.swing.JRadioButton radioTecnoNo;
    private javax.swing.JRadioButton radioTecnoSi;
    private javax.swing.JTextField txtCantidadSillas;
    private javax.swing.JTextField txtPlaca;
    private javax.swing.JTextField txtTipoBus;
    // End of variables declaration//GEN-END:variables
}
