/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Guis;

import Modelos.Pasajero;
import Modelos.Persona;
import Modelos.buses;
import java.awt.Color;
import java.awt.Label;
import java.awt.event.ItemEvent;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JhonLegends
 */
public class ReservaGui extends javax.swing.JFrame {

    public busSilla buSillas = new busSilla();
    Label[] puesto;
    
    buses objBuses = new buses();
    int PorcentajeOcupacion = 0;
    buses []vectorBuses;
    int cantidadSillas;
    int pos;
    DefaultTableModel tablaPuesto;
    public ReservaGui() {
        initComponents();
        lbEscogerBus.setEnabled(false);
//        lbNumeroPuesto.setEnabled(false);
//        txtPuesto.setEnabled(false);
        cbBus.setEnabled(false);
//        lbInformacion.setEnabled(false);
        vectorBuses=objBuses.getObjBuses();
        pos=0;
        obtenerBus();
        cantidadSillas=0;
        
        puesto = new Label[50];
        puesto[0] = label1;
        puesto[1] = label2;
        puesto[2] = label3;
        puesto[3] = label4;
        puesto[4] = label5;
        puesto[5] = label6;
        puesto[6] = label7;
        puesto[7] = label8;
        puesto[8] = label9;
        puesto[9] = label10;
        puesto[10] = label11;
        puesto[11] = label12;
        puesto[12] = label13;
        puesto[13] = label14;
        puesto[14] = label15;
        puesto[15] = label16;
        puesto[16] = label17;
        puesto[17] = label18;
        puesto[18] = label19;
        puesto[19] = label20;
        puesto[20] = label21;
        puesto[21] = label22;
        puesto[22] = label23;
        puesto[23] = label24;
        puesto[24] = label25;
        puesto[25] = label26;
        puesto[26] = label27;
        puesto[27] = label28;
        puesto[28] = label29;
        puesto[29] = label30;
        puesto[30] = label31;
        puesto[31] = label32;
        puesto[32] = label33;
        puesto[33] = label34;
        puesto[34] = label35;
        puesto[35] = label36;
        puesto[36] = label37;
        puesto[37] = label38;
        puesto[38] = label39;
        puesto[39] = label40;
        puesto[40] = label41;
        puesto[41] = label42;
        puesto[42] = label43;
        puesto[43] = label44;
        puesto[44] = label45;
        puesto[45] = label46;
        puesto[46] = label47;
        puesto[47] = label48;
        puesto[48] = label49;
        puesto[49] = label50;
    }
    public String[] getPosicion(String Clase) {

        String[] Posicion = new String[4];
        if ("Ejecutiva".equals(Clase)) {
            Posicion[0] = "Seleccione..";
            Posicion[1] = "Ventana";
            Posicion[2] = "Pasillo";
        } else if ("Economica".equals(Clase)) {
            Posicion[0] = "Seleccione..";
            Posicion[1] = "Ventana";
            Posicion[2] = "Pasillo";
        }
        return Posicion;
    }
    
        public String[] getSillas(String Clase, String Posicion) {
        int tamDisponibilidad = 0;
        String[] sillon = new String[49];
        for (int i = 0; i <= 49; i++) {
            if (buSillas.silla[i].disponibilidad == true && buSillas.silla[i].clase.equals(Clase) && buSillas.silla[i].posicion.equals(Posicion)) {
                sillon[tamDisponibilidad] = String.valueOf(buSillas.silla[i].numero);
                tamDisponibilidad += 1;
            }
        }
        return sillon;

    }
        
    public busSilla getbusSilla() {
        return buSillas;
    }

    public void setbusSilla(busSilla silla) {
        this.buSillas = silla;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label5 = new java.awt.Label();
        label6 = new java.awt.Label();
        jtpBus = new javax.swing.JTabbedPane();
        jpReserva = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        cbBus = new javax.swing.JComboBox<String>();
        lbEscogerBus = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jBoxClase = new javax.swing.JComboBox<String>();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jBoxSilla = new javax.swing.JComboBox<String>();
        jBoxPosicion = new javax.swing.JComboBox<String>();
        jLabel11 = new javax.swing.JLabel();
        jLabelPrecio = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        label7 = new java.awt.Label();
        label8 = new java.awt.Label();
        label9 = new java.awt.Label();
        label10 = new java.awt.Label();
        label11 = new java.awt.Label();
        label12 = new java.awt.Label();
        label13 = new java.awt.Label();
        label14 = new java.awt.Label();
        label15 = new java.awt.Label();
        label16 = new java.awt.Label();
        label17 = new java.awt.Label();
        label18 = new java.awt.Label();
        label19 = new java.awt.Label();
        label20 = new java.awt.Label();
        label21 = new java.awt.Label();
        label22 = new java.awt.Label();
        label23 = new java.awt.Label();
        label24 = new java.awt.Label();
        label25 = new java.awt.Label();
        label26 = new java.awt.Label();
        label27 = new java.awt.Label();
        label28 = new java.awt.Label();
        label29 = new java.awt.Label();
        label30 = new java.awt.Label();
        label31 = new java.awt.Label();
        label32 = new java.awt.Label();
        label33 = new java.awt.Label();
        label34 = new java.awt.Label();
        label35 = new java.awt.Label();
        label36 = new java.awt.Label();
        label37 = new java.awt.Label();
        label38 = new java.awt.Label();
        label39 = new java.awt.Label();
        label40 = new java.awt.Label();
        label41 = new java.awt.Label();
        label42 = new java.awt.Label();
        label43 = new java.awt.Label();
        label44 = new java.awt.Label();
        label45 = new java.awt.Label();
        label46 = new java.awt.Label();
        label47 = new java.awt.Label();
        label48 = new java.awt.Label();
        label49 = new java.awt.Label();
        label50 = new java.awt.Label();
        label51 = new java.awt.Label();
        label52 = new java.awt.Label();
        label53 = new java.awt.Label();
        label54 = new java.awt.Label();
        jLabel2 = new javax.swing.JLabel();
        jLabelPorcentajeO = new javax.swing.JLabel();

        label1.setBackground(new java.awt.Color(153, 153, 153));
        label1.setText("  ");

        label2.setBackground(new java.awt.Color(153, 153, 153));
        label2.setText("  ");

        label5.setBackground(new java.awt.Color(153, 153, 153));
        label5.setText("  ");

        label6.setBackground(new java.awt.Color(153, 153, 153));
        label6.setText("  ");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpReserva.setEnabled(false);

        jLabel7.setFont(new java.awt.Font("Verdana", 2, 24)); // NOI18N
        jLabel7.setText("RESERVA");

        jLabel8.setText("CEDULA CLIENTE:");

        txtCedula.setEditable(false);
        txtCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaActionPerformed(evt);
            }
        });

        jLabel9.setText("NOMBRE CLIENTE:");

        txtNombre.setEditable(false);
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        cbBus.setEnabled(false);
        cbBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBusActionPerformed(evt);
            }
        });

        lbEscogerBus.setText("PLACA DEL BUS");
        lbEscogerBus.setEnabled(false);

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N
        btnBuscar.setText("BUSCAR CLIENTE");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/return.png"))); // NOI18N
        btnAtras.setText("Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        jLabel4.setText("CLASE:");

        jBoxClase.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "- Seleccione -", "Economica", "Ejecutiva" }));
        jBoxClase.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jBoxClaseItemStateChanged(evt);
            }
        });
        jBoxClase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBoxClaseActionPerformed(evt);
            }
        });

        jLabel5.setText("POSICION:");

        jLabel10.setText("SILLA:");

        jBoxSilla.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "- Seleccione -" }));
        jBoxSilla.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jBoxSillaItemStateChanged(evt);
            }
        });
        jBoxSilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBoxSillaActionPerformed(evt);
            }
        });

        jBoxPosicion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "- Seleccione -" }));
        jBoxPosicion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jBoxPosicionItemStateChanged(evt);
            }
        });
        jBoxPosicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBoxPosicionActionPerformed(evt);
            }
        });

        jLabel11.setText("Valor:");

        jLabelPrecio.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabelPrecio.setText("0 $");

        btnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save.png"))); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpReservaLayout = new javax.swing.GroupLayout(jpReserva);
        jpReserva.setLayout(jpReservaLayout);
        jpReservaLayout.setHorizontalGroup(
            jpReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpReservaLayout.createSequentialGroup()
                .addGroup(jpReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpReservaLayout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpReservaLayout.createSequentialGroup()
                        .addGroup(jpReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpReservaLayout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(jpReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbEscogerBus)
                                    .addComponent(jLabel11)))
                            .addGroup(jpReservaLayout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addGroup(jpReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel10))))
                        .addGap(31, 31, 31)
                        .addGroup(jpReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpReservaLayout.createSequentialGroup()
                                .addComponent(jLabelPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(44, 44, 44)
                                .addComponent(btnRegistrar)
                                .addGap(66, 66, 66))
                            .addComponent(txtNombre)
                            .addComponent(jBoxClase, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCedula)
                            .addComponent(jBoxPosicion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbBus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBoxSilla, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(33, 33, 33)
                .addGroup(jpReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBuscar)
                    .addComponent(btnAtras))
                .addGap(140, 140, 140))
        );
        jpReservaLayout.setVerticalGroup(
            jpReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpReservaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel7)
                .addGap(42, 42, 42)
                .addGroup(jpReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jpReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpReservaLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jpReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpReservaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar)
                        .addGap(6, 6, 6)))
                .addGroup(jpReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jBoxClase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jBoxPosicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jBoxSilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jpReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpReservaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addGroup(jpReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbBus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbEscogerBus))
                        .addGap(18, 18, 18))
                    .addGroup(jpReservaLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnAtras)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)))
                .addGroup(jpReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpReservaLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel11))
                    .addComponent(jLabelPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpReservaLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btnRegistrar)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jtpBus.addTab("Reserva pasajeros", jpReserva);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(null);

        label3.setBackground(new java.awt.Color(153, 153, 153));
        label3.setText("  ");
        jPanel4.add(label3);
        label3.setBounds(480, 190, 20, 20);

        label4.setBackground(new java.awt.Color(153, 153, 153));
        label4.setText("  ");
        jPanel4.add(label4);
        label4.setBounds(480, 210, 20, 20);

        label7.setBackground(new java.awt.Color(153, 153, 153));
        label7.setText("  ");
        jPanel4.add(label7);
        label7.setBounds(480, 110, 20, 20);

        label8.setBackground(new java.awt.Color(153, 153, 153));
        label8.setText("  ");
        jPanel4.add(label8);
        label8.setBounds(480, 130, 20, 20);

        label9.setBackground(new java.awt.Color(153, 153, 153));
        label9.setText("  ");
        jPanel4.add(label9);
        label9.setBounds(450, 190, 20, 20);

        label10.setBackground(new java.awt.Color(153, 153, 153));
        label10.setText("  ");
        jPanel4.add(label10);
        label10.setBounds(450, 210, 20, 20);

        label11.setBackground(new java.awt.Color(153, 153, 153));
        label11.setText("  ");
        jPanel4.add(label11);
        label11.setBounds(450, 110, 20, 20);

        label12.setBackground(new java.awt.Color(153, 153, 153));
        label12.setText("  ");
        jPanel4.add(label12);
        label12.setBounds(450, 130, 20, 20);

        label13.setBackground(new java.awt.Color(153, 153, 153));
        label13.setText("  ");
        jPanel4.add(label13);
        label13.setBounds(380, 210, 20, 20);

        label14.setBackground(new java.awt.Color(153, 153, 153));
        label14.setText("  ");
        jPanel4.add(label14);
        label14.setBounds(410, 190, 20, 20);

        label15.setBackground(new java.awt.Color(153, 153, 153));
        label15.setText("  ");
        jPanel4.add(label15);
        label15.setBounds(410, 210, 20, 20);

        label16.setBackground(new java.awt.Color(153, 153, 153));
        label16.setText("  ");
        jPanel4.add(label16);
        label16.setBounds(410, 110, 20, 20);

        label17.setBackground(new java.awt.Color(153, 153, 153));
        label17.setText("  ");
        jPanel4.add(label17);
        label17.setBounds(410, 130, 20, 20);

        label18.setBackground(new java.awt.Color(153, 153, 153));
        label18.setText("  ");
        jPanel4.add(label18);
        label18.setBounds(380, 110, 20, 20);

        label19.setBackground(new java.awt.Color(153, 153, 153));
        label19.setText("  ");
        jPanel4.add(label19);
        label19.setBounds(380, 190, 20, 20);

        label20.setBackground(new java.awt.Color(153, 153, 153));
        label20.setText("  ");
        jPanel4.add(label20);
        label20.setBounds(350, 190, 20, 20);

        label21.setBackground(new java.awt.Color(153, 153, 153));
        label21.setText("  ");
        jPanel4.add(label21);
        label21.setBounds(350, 210, 20, 20);

        label22.setBackground(new java.awt.Color(153, 153, 153));
        label22.setText("  ");
        jPanel4.add(label22);
        label22.setBounds(380, 130, 20, 20);

        label23.setBackground(new java.awt.Color(153, 153, 153));
        label23.setText("  ");
        jPanel4.add(label23);
        label23.setBounds(340, 110, 20, 20);

        label24.setBackground(new java.awt.Color(153, 153, 153));
        label24.setText("  ");
        jPanel4.add(label24);
        label24.setBounds(340, 130, 20, 20);

        label25.setBackground(new java.awt.Color(153, 153, 153));
        label25.setText("  ");
        jPanel4.add(label25);
        label25.setBounds(310, 210, 20, 20);

        label26.setBackground(new java.awt.Color(153, 153, 153));
        label26.setText("  ");
        jPanel4.add(label26);
        label26.setBounds(280, 210, 20, 20);

        label27.setBackground(new java.awt.Color(153, 153, 153));
        label27.setText("  ");
        jPanel4.add(label27);
        label27.setBounds(310, 190, 20, 20);

        label28.setBackground(new java.awt.Color(153, 153, 153));
        label28.setText("  ");
        jPanel4.add(label28);
        label28.setBounds(310, 110, 20, 20);

        label29.setBackground(new java.awt.Color(153, 153, 153));
        label29.setText("  ");
        jPanel4.add(label29);
        label29.setBounds(310, 130, 20, 20);

        label30.setBackground(new java.awt.Color(153, 153, 153));
        label30.setText("  ");
        jPanel4.add(label30);
        label30.setBounds(270, 110, 20, 20);

        label31.setBackground(new java.awt.Color(153, 153, 153));
        label31.setText("  ");
        jPanel4.add(label31);
        label31.setBounds(280, 190, 20, 20);

        label32.setBackground(new java.awt.Color(153, 153, 153));
        label32.setText("  ");
        jPanel4.add(label32);
        label32.setBounds(250, 190, 20, 20);

        label33.setBackground(new java.awt.Color(153, 153, 153));
        label33.setText("  ");
        jPanel4.add(label33);
        label33.setBounds(250, 210, 20, 20);

        label34.setBackground(new java.awt.Color(153, 153, 153));
        label34.setText("  ");
        jPanel4.add(label34);
        label34.setBounds(270, 130, 20, 20);

        label35.setBackground(new java.awt.Color(153, 153, 153));
        label35.setText("  ");
        jPanel4.add(label35);
        label35.setBounds(240, 110, 20, 20);

        label36.setBackground(new java.awt.Color(153, 153, 153));
        label36.setText("  ");
        jPanel4.add(label36);
        label36.setBounds(240, 130, 20, 20);

        label37.setBackground(new java.awt.Color(153, 153, 153));
        label37.setText("  ");
        jPanel4.add(label37);
        label37.setBounds(210, 190, 20, 20);

        label38.setBackground(new java.awt.Color(153, 153, 153));
        label38.setText("  ");
        jPanel4.add(label38);
        label38.setBounds(210, 210, 20, 20);

        label39.setBackground(new java.awt.Color(153, 153, 153));
        label39.setText("  ");
        jPanel4.add(label39);
        label39.setBounds(180, 190, 20, 20);

        label40.setBackground(new java.awt.Color(153, 153, 153));
        label40.setText("  ");
        jPanel4.add(label40);
        label40.setBounds(210, 110, 20, 20);

        label41.setBackground(new java.awt.Color(153, 153, 153));
        label41.setText("  ");
        jPanel4.add(label41);
        label41.setBounds(210, 130, 20, 20);

        label42.setBackground(new java.awt.Color(153, 153, 153));
        label42.setText("  ");
        jPanel4.add(label42);
        label42.setBounds(170, 110, 20, 20);

        label43.setBackground(new java.awt.Color(153, 153, 153));
        label43.setText("  ");
        jPanel4.add(label43);
        label43.setBounds(150, 210, 20, 20);

        label44.setBackground(new java.awt.Color(153, 153, 153));
        label44.setText("  ");
        jPanel4.add(label44);
        label44.setBounds(150, 190, 20, 20);

        label45.setBackground(new java.awt.Color(153, 153, 153));
        label45.setText("  ");
        jPanel4.add(label45);
        label45.setBounds(180, 210, 20, 20);

        label46.setBackground(new java.awt.Color(153, 153, 153));
        label46.setText("  ");
        jPanel4.add(label46);
        label46.setBounds(170, 130, 20, 20);

        label47.setBackground(new java.awt.Color(153, 153, 153));
        label47.setText("  ");
        jPanel4.add(label47);
        label47.setBounds(130, 110, 20, 20);

        label48.setBackground(new java.awt.Color(153, 153, 153));
        label48.setText("  ");
        jPanel4.add(label48);
        label48.setBounds(130, 130, 20, 20);

        label49.setBackground(new java.awt.Color(153, 153, 153));
        label49.setText("  ");
        jPanel4.add(label49);
        label49.setBounds(110, 190, 20, 20);

        label50.setBackground(new java.awt.Color(153, 153, 153));
        label50.setText("  ");
        jPanel4.add(label50);
        label50.setBounds(110, 210, 20, 20);

        label51.setBackground(new java.awt.Color(153, 153, 153));
        label51.setText("  ");
        jPanel4.add(label51);
        label51.setBounds(60, 130, 20, 20);

        label52.setBackground(new java.awt.Color(153, 153, 153));
        label52.setText("  ");
        jPanel4.add(label52);
        label52.setBounds(100, 110, 20, 20);

        label53.setBackground(new java.awt.Color(153, 153, 153));
        label53.setText("  ");
        jPanel4.add(label53);
        label53.setBounds(100, 130, 20, 20);

        label54.setBackground(new java.awt.Color(153, 153, 153));
        label54.setText("  ");
        jPanel4.add(label54);
        label54.setBounds(60, 110, 20, 20);

        jLabel2.setBackground(new java.awt.Color(255, 0, 102));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/busFondo.png"))); // NOI18N
        jLabel2.setText("dvdsd");
        jPanel4.add(jLabel2);
        jLabel2.setBounds(20, 70, 620, 210);

        jLabelPorcentajeO.setBackground(new java.awt.Color(0, 0, 0));
        jLabelPorcentajeO.setFont(new java.awt.Font("Tahoma", 0, 50)); // NOI18N
        jLabelPorcentajeO.setText("       0 %");
        jPanel4.add(jLabelPorcentajeO);
        jLabelPorcentajeO.setBounds(430, 240, 240, 170);

        jtpBus.addTab("Bus", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtpBus))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtpBus)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        String Nombre = txtNombre.getText();
        String Cedula = txtCedula.getText();
        System.out.println(Nombre);
        System.out.println(Cedula);
        int Numero = Integer.parseInt((String) jBoxSilla.getSelectedItem());
        Pasajero pasajero = new Pasajero();
        pasajero.setNombre(Nombre);
        pasajero.setCedula(Cedula);
        buSillas.silla[Numero - 1].disponibilidad = false;
        buSillas.silla[Numero - 1].setPasajero(pasajero);
        System.out.println(buSillas);
        System.out.println(pasajero);
        txtNombre.setText("");
        txtCedula.setText("");
        jBoxClase.setSelectedIndex(0);
        jBoxPosicion.removeAllItems();
        jBoxSilla.removeAllItems();
        String PorDisponible = String.valueOf((Ocupacion() * 100) / 50) + "%";
        jLabelPorcentajeO.setText(PorDisponible);
        jLabelPrecio.setText("0$");
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void jBoxPosicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBoxPosicionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBoxPosicionActionPerformed

    private void jBoxPosicionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jBoxPosicionItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            this.jBoxSilla.setModel(new DefaultComboBoxModel(this.getSillas((this.jBoxClase.getSelectedItem().toString()),
                this.jBoxPosicion.getSelectedItem().toString())));
    }
    }//GEN-LAST:event_jBoxPosicionItemStateChanged

    private void jBoxSillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBoxSillaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBoxSillaActionPerformed

    private void jBoxSillaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jBoxSillaItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            int p = Integer.parseInt(this.jBoxSilla.getSelectedItem().toString());
            int precio = buSillas.silla[p - 1].getPrecio();
            this.jLabelPrecio.setText(String.valueOf(precio));
        }
    }//GEN-LAST:event_jBoxSillaItemStateChanged

    private void jBoxClaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBoxClaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBoxClaseActionPerformed

    private void jBoxClaseItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jBoxClaseItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            this.jBoxPosicion.setModel(new DefaultComboBoxModel(this.getPosicion(this.jBoxClase.getSelectedItem().toString())));
        }
    }//GEN-LAST:event_jBoxClaseItemStateChanged

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        Menu btnAtras = new Menu();
        btnAtras.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        String cedula = JOptionPane.showInputDialog(this, "Ingrese el NIT");
        boolean bandera=false;
        Pasajero objPasajero2 = new Pasajero();
        Pasajero[] buscarPasajero = objPasajero2.getObjPasajero();
        for (int i = 0; i < buscarPasajero.length; i++) {
            if (buscarPasajero[i].getCedulaPersona().equals(cedula)) {
                txtNombre.setText(buscarPasajero[i].getNombrePersona());
                txtCedula.setText(buscarPasajero[i].getCedulaPersona());
                lbEscogerBus.setEnabled(true);
                cbBus.setEnabled(true);
                bandera=true;
                break;
            }
        }
        if(!bandera){
            JOptionPane.showMessageDialog(this, "Cliente no Encontrado");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void cbBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbBusActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaActionPerformed
    public void obtenerBus(){
        
        for(int i=0; i<vectorBuses.length;i++){
            if(vectorBuses[i]!=null){
                cbBus.addItem(vectorBuses[i].getPlaca());
            }
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReservaGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReservaGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReservaGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReservaGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReservaGui().setVisible(true);
            }
        });
    }
    public int Ocupacion() {
        int CuentaSillascupadas = 0;
        for (int i = 0; i <= 49; i++) {
            if (buSillas.silla[i].isDisponibilidad() == false) {
                puesto[i].setBackground(Color.RED);
                CuentaSillascupadas++;
            } else {
                puesto[i].setBackground(Color.CYAN);
            }
        }
        return CuentaSillascupadas;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cbBus;
    private javax.swing.JComboBox<String> jBoxClase;
    private javax.swing.JComboBox<String> jBoxPosicion;
    private javax.swing.JComboBox<String> jBoxSilla;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelPorcentajeO;
    private javax.swing.JLabel jLabelPrecio;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jpReserva;
    private javax.swing.JTabbedPane jtpBus;
    private java.awt.Label label1;
    private java.awt.Label label10;
    private java.awt.Label label11;
    private java.awt.Label label12;
    private java.awt.Label label13;
    private java.awt.Label label14;
    private java.awt.Label label15;
    private java.awt.Label label16;
    private java.awt.Label label17;
    private java.awt.Label label18;
    private java.awt.Label label19;
    private java.awt.Label label2;
    private java.awt.Label label20;
    private java.awt.Label label21;
    private java.awt.Label label22;
    private java.awt.Label label23;
    private java.awt.Label label24;
    private java.awt.Label label25;
    private java.awt.Label label26;
    private java.awt.Label label27;
    private java.awt.Label label28;
    private java.awt.Label label29;
    private java.awt.Label label3;
    private java.awt.Label label30;
    private java.awt.Label label31;
    private java.awt.Label label32;
    private java.awt.Label label33;
    private java.awt.Label label34;
    private java.awt.Label label35;
    private java.awt.Label label36;
    private java.awt.Label label37;
    private java.awt.Label label38;
    private java.awt.Label label39;
    private java.awt.Label label4;
    private java.awt.Label label40;
    private java.awt.Label label41;
    private java.awt.Label label42;
    private java.awt.Label label43;
    private java.awt.Label label44;
    private java.awt.Label label45;
    private java.awt.Label label46;
    private java.awt.Label label47;
    private java.awt.Label label48;
    private java.awt.Label label49;
    private java.awt.Label label5;
    private java.awt.Label label50;
    private java.awt.Label label51;
    private java.awt.Label label52;
    private java.awt.Label label53;
    private java.awt.Label label54;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Label label9;
    private javax.swing.JLabel lbEscogerBus;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
