/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Guis;

import Modelos.busSilla;
import Modelos.Silla;
import Modelos.Pasajero;
import Modelos.Persona;
import Modelos.buses;
import java.awt.Color;
import java.awt.Label;
import java.awt.event.ItemEvent;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JhonLegends
 */
public class ReservaGui extends javax.swing.JFrame {

    
    Label[] puesto;
    
    buses objBuses = new buses();
    int PorcentajeOcupacion = 0;
    buses []vectorBuses;
    int cantidadSillas;
    int pos;
    public busSilla buSillas = new busSilla();
    public ReservaGui() {
        initComponents();
        
//        lbNumeroPuesto.setEnabled(false);
//        txtPuesto.setEnabled(false);
        
//        lbInformacion.setEnabled(false);
        vectorBuses=objBuses.getObjBuses();
        pos=0;
        obtenerBus();
        cantidadSillas=0;
        
    
        puesto = new Label[50];
        
        puesto[0] = lb1;
        puesto[1] = lb2;
        puesto[2] = lb3;
        puesto[3] = lb4;
        puesto[4] = lb5;
        puesto[5] = lb6;
        puesto[6] = lb7;
        puesto[7] = lb8;
        puesto[8] = lb9;
        puesto[9] = lb10;
        puesto[10] = lb11;
        puesto[11] = lb12;
        puesto[12] = lb13;
        puesto[13] = lb14;
        puesto[14] = lb15;
        puesto[15] = lb16;
        puesto[16] = lb17;
        puesto[17] = lb18;
        puesto[18] = lb19;
        puesto[19] = lb20;
        puesto[20] = lb21;
        puesto[21] = lb22;
        puesto[22] = lb23;
        puesto[23] = lb24;
        puesto[24] = lb25;
        puesto[25] = lb26;
        puesto[26] = lb27;
        puesto[27] = lb28;
        puesto[28] = lb29;
        puesto[29] = lb30;
        puesto[30] = lb31;
        puesto[31] = lb32;
        puesto[32] = lb33;
        puesto[33] = lb34;
        puesto[34] = lb35;
        puesto[35] = lb36;
        puesto[36] = lb37;
        puesto[37] = lb38;
        puesto[38] = lb39;
        puesto[39] = lb40;
        puesto[40] = lb41;
        puesto[41] = lb42;
        puesto[42] = lb43;
        puesto[43] = lb44;
        puesto[44] = lb45;
        puesto[45] = lb46;
        puesto[46] = lb47;
        puesto[47] = lb48;
        puesto[48] = lb49;
        puesto[49] = lb50;
    }
    public String[] getPosicion(String Clase) {

        String[] Posicion = new String[4];
        if ("Ejecutiva".equals(Clase)) {
            Posicion[0] = "Seleccione..";
            Posicion[1] = "Ventana";
            Posicion[2] = "Pasillo";
        } else if ("Economica".equals(Clase)) {
            Posicion[0] = "Seleccione..";
            Posicion[1] = "Ventana";
            Posicion[2] = "Pasillo";
        }
        return Posicion;
    }
    
        public String[] getSillas(String Clase, String Posicion) {
        int tamDisponibilidad = 0;
        String[] sillon = new String[49];
        for (int i = 0; i <= 49; i++) {
            if (buSillas.getSilla()[i].isDisponibilidad() == true && buSillas.getSilla()[i].getClase().equals(Clase) && buSillas.getSilla()[i].getPosicion().equals(Posicion)) {
                sillon[tamDisponibilidad] = String.valueOf(buSillas.getSilla()[i].getNumero());
                tamDisponibilidad += 1;
            }
        }
        return sillon;

    }
        
    public busSilla getbusSilla() {
        return buSillas;
    }

    public void setbusSilla(busSilla silla) {
        this.buSillas = silla;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label5 = new java.awt.Label();
        label6 = new java.awt.Label();
        jtpBus = new javax.swing.JTabbedPane();
        jpReserva = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        cbBus = new javax.swing.JComboBox<String>();
        lbEscogerBus = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jBoxClase = new javax.swing.JComboBox<String>();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jBoxSilla = new javax.swing.JComboBox<String>();
        jBoxPosicion = new javax.swing.JComboBox<String>();
        jLabel11 = new javax.swing.JLabel();
        jLabelPrecio = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lb3 = new java.awt.Label();
        lb4 = new java.awt.Label();
        lb1 = new java.awt.Label();
        lb2 = new java.awt.Label();
        lb7 = new java.awt.Label();
        lb8 = new java.awt.Label();
        lb5 = new java.awt.Label();
        lb6 = new java.awt.Label();
        lb16 = new java.awt.Label();
        lb11 = new java.awt.Label();
        lb12 = new java.awt.Label();
        lb9 = new java.awt.Label();
        lb10 = new java.awt.Label();
        lb13 = new java.awt.Label();
        lb15 = new java.awt.Label();
        lb19 = new java.awt.Label();
        lb20 = new java.awt.Label();
        lb14 = new java.awt.Label();
        lb17 = new java.awt.Label();
        lb18 = new java.awt.Label();
        lb24 = new java.awt.Label();
        lb28 = new java.awt.Label();
        lb23 = new java.awt.Label();
        lb21 = new java.awt.Label();
        lb22 = new java.awt.Label();
        lb25 = new java.awt.Label();
        lb27 = new java.awt.Label();
        lb31 = new java.awt.Label();
        lb32 = new java.awt.Label();
        lb26 = new java.awt.Label();
        lb29 = new java.awt.Label();
        lb30 = new java.awt.Label();
        lb35 = new java.awt.Label();
        lb36 = new java.awt.Label();
        lb39 = new java.awt.Label();
        lb33 = new java.awt.Label();
        lb34 = new java.awt.Label();
        lb37 = new java.awt.Label();
        lb44 = new java.awt.Label();
        lb43 = new java.awt.Label();
        lb40 = new java.awt.Label();
        lb38 = new java.awt.Label();
        lb41 = new java.awt.Label();
        lb42 = new java.awt.Label();
        lb47 = new java.awt.Label();
        lb48 = new java.awt.Label();
        lb50 = new java.awt.Label();
        lb45 = new java.awt.Label();
        lb46 = new java.awt.Label();
        lb49 = new java.awt.Label();
        jLabel2 = new javax.swing.JLabel();
        jLabelPorcentajeO = new javax.swing.JLabel();

        label1.setBackground(new java.awt.Color(153, 153, 153));
        label1.setText("  ");

        label2.setBackground(new java.awt.Color(153, 153, 153));
        label2.setText("  ");

        label5.setBackground(new java.awt.Color(153, 153, 153));
        label5.setText("  ");

        label6.setBackground(new java.awt.Color(153, 153, 153));
        label6.setText("  ");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpReserva.setEnabled(false);

        jLabel7.setFont(new java.awt.Font("Verdana", 2, 24)); // NOI18N
        jLabel7.setText("RESERVA");

        jLabel8.setText("CEDULA CLIENTE:");

        txtCedula.setEditable(false);
        txtCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaActionPerformed(evt);
            }
        });

        jLabel9.setText("NOMBRE CLIENTE:");

        txtNombre.setEditable(false);
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        cbBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBusActionPerformed(evt);
            }
        });

        lbEscogerBus.setText("PLACA DEL BUS");

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N
        btnBuscar.setText("BUSCAR CLIENTE");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/return.png"))); // NOI18N
        btnAtras.setText("Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        jLabel4.setText("CLASE:");

        jBoxClase.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "- Seleccione -", "Economica", "Ejecutiva" }));
        jBoxClase.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jBoxClaseItemStateChanged(evt);
            }
        });
        jBoxClase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBoxClaseActionPerformed(evt);
            }
        });

        jLabel5.setText("POSICION:");

        jLabel10.setText("SILLA:");

        jBoxSilla.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "- Seleccione -" }));
        jBoxSilla.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jBoxSillaItemStateChanged(evt);
            }
        });
        jBoxSilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBoxSillaActionPerformed(evt);
            }
        });

        jBoxPosicion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "- Seleccione -" }));
        jBoxPosicion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jBoxPosicionItemStateChanged(evt);
            }
        });
        jBoxPosicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBoxPosicionActionPerformed(evt);
            }
        });

        jLabel11.setText("Valor:");

        jLabelPrecio.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabelPrecio.setText("0 $");

        btnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save.png"))); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpReservaLayout = new javax.swing.GroupLayout(jpReserva);
        jpReserva.setLayout(jpReservaLayout);
        jpReservaLayout.setHorizontalGroup(
            jpReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpReservaLayout.createSequentialGroup()
                .addGroup(jpReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpReservaLayout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpReservaLayout.createSequentialGroup()
                        .addGroup(jpReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpReservaLayout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(jpReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11)
                                    .addGroup(jpReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbEscogerBus)
                                        .addComponent(jLabel8))))
                            .addGroup(jpReservaLayout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addGroup(jpReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel10))))
                        .addGap(31, 31, 31)
                        .addGroup(jpReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpReservaLayout.createSequentialGroup()
                                .addComponent(jLabelPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                                .addGap(44, 44, 44)
                                .addComponent(btnRegistrar)
                                .addGap(66, 66, 66))
                            .addComponent(txtNombre)
                            .addComponent(jBoxClase, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCedula)
                            .addComponent(cbBus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jpReservaLayout.createSequentialGroup()
                                .addComponent(jBoxPosicion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBoxSilla, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBuscar)
                    .addComponent(btnAtras))
                .addGap(140, 140, 140))
        );
        jpReservaLayout.setVerticalGroup(
            jpReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpReservaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel7)
                .addGap(4, 4, 4)
                .addGroup(jpReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbBus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbEscogerBus))
                .addGap(18, 18, 18)
                .addGroup(jpReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jpReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpReservaLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jpReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpReservaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar)
                        .addGap(6, 6, 6)))
                .addGroup(jpReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jBoxClase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jBoxPosicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBoxSilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(6, 6, 6)
                .addComponent(btnAtras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jpReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpReservaLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel11))
                    .addComponent(jLabelPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpReservaLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btnRegistrar)))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jtpBus.addTab("Reserva pasajeros", jpReserva);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(null);

        lb3.setBackground(new java.awt.Color(153, 153, 153));
        lb3.setText("  ");
        jPanel4.add(lb3);
        lb3.setBounds(480, 190, 20, 20);

        lb4.setBackground(new java.awt.Color(153, 153, 153));
        lb4.setText("  ");
        jPanel4.add(lb4);
        lb4.setBounds(480, 210, 20, 20);

        lb1.setBackground(new java.awt.Color(153, 153, 153));
        lb1.setText("  ");
        jPanel4.add(lb1);
        lb1.setBounds(480, 110, 20, 20);

        lb2.setBackground(new java.awt.Color(153, 153, 153));
        lb2.setText("  ");
        jPanel4.add(lb2);
        lb2.setBounds(480, 130, 20, 20);

        lb7.setBackground(new java.awt.Color(153, 153, 153));
        lb7.setText("  ");
        jPanel4.add(lb7);
        lb7.setBounds(450, 190, 20, 20);

        lb8.setBackground(new java.awt.Color(153, 153, 153));
        lb8.setText("  ");
        jPanel4.add(lb8);
        lb8.setBounds(450, 210, 20, 20);

        lb5.setBackground(new java.awt.Color(153, 153, 153));
        lb5.setText("  ");
        jPanel4.add(lb5);
        lb5.setBounds(450, 110, 20, 20);

        lb6.setBackground(new java.awt.Color(153, 153, 153));
        lb6.setText("  ");
        jPanel4.add(lb6);
        lb6.setBounds(450, 130, 20, 20);

        lb16.setBackground(new java.awt.Color(153, 153, 153));
        lb16.setText("  ");
        jPanel4.add(lb16);
        lb16.setBounds(380, 210, 20, 20);

        lb11.setBackground(new java.awt.Color(153, 153, 153));
        lb11.setText("  ");
        jPanel4.add(lb11);
        lb11.setBounds(410, 190, 20, 20);

        lb12.setBackground(new java.awt.Color(153, 153, 153));
        lb12.setText("  ");
        jPanel4.add(lb12);
        lb12.setBounds(410, 210, 20, 20);

        lb9.setBackground(new java.awt.Color(153, 153, 153));
        lb9.setText("  ");
        jPanel4.add(lb9);
        lb9.setBounds(410, 110, 20, 20);

        lb10.setBackground(new java.awt.Color(153, 153, 153));
        lb10.setText("  ");
        jPanel4.add(lb10);
        lb10.setBounds(410, 130, 20, 20);

        lb13.setBackground(new java.awt.Color(153, 153, 153));
        lb13.setText("  ");
        jPanel4.add(lb13);
        lb13.setBounds(380, 110, 20, 20);

        lb15.setBackground(new java.awt.Color(153, 153, 153));
        lb15.setText("  ");
        jPanel4.add(lb15);
        lb15.setBounds(380, 190, 20, 20);

        lb19.setBackground(new java.awt.Color(153, 153, 153));
        lb19.setText("  ");
        jPanel4.add(lb19);
        lb19.setBounds(350, 190, 20, 20);

        lb20.setBackground(new java.awt.Color(153, 153, 153));
        lb20.setText("  ");
        jPanel4.add(lb20);
        lb20.setBounds(350, 210, 20, 20);

        lb14.setBackground(new java.awt.Color(153, 153, 153));
        lb14.setText("  ");
        jPanel4.add(lb14);
        lb14.setBounds(380, 130, 20, 20);

        lb17.setBackground(new java.awt.Color(153, 153, 153));
        lb17.setText("  ");
        jPanel4.add(lb17);
        lb17.setBounds(340, 110, 20, 20);

        lb18.setBackground(new java.awt.Color(153, 153, 153));
        lb18.setText("  ");
        jPanel4.add(lb18);
        lb18.setBounds(340, 130, 20, 20);

        lb24.setBackground(new java.awt.Color(153, 153, 153));
        lb24.setText("  ");
        jPanel4.add(lb24);
        lb24.setBounds(310, 210, 20, 20);

        lb28.setBackground(new java.awt.Color(153, 153, 153));
        lb28.setText("  ");
        jPanel4.add(lb28);
        lb28.setBounds(280, 210, 20, 20);

        lb23.setBackground(new java.awt.Color(153, 153, 153));
        lb23.setText("  ");
        jPanel4.add(lb23);
        lb23.setBounds(310, 190, 20, 20);

        lb21.setBackground(new java.awt.Color(153, 153, 153));
        lb21.setText("  ");
        jPanel4.add(lb21);
        lb21.setBounds(310, 110, 20, 20);

        lb22.setBackground(new java.awt.Color(153, 153, 153));
        lb22.setText("  ");
        jPanel4.add(lb22);
        lb22.setBounds(310, 130, 20, 20);

        lb25.setBackground(new java.awt.Color(153, 153, 153));
        lb25.setText("  ");
        jPanel4.add(lb25);
        lb25.setBounds(270, 110, 20, 20);

        lb27.setBackground(new java.awt.Color(153, 153, 153));
        lb27.setText("  ");
        jPanel4.add(lb27);
        lb27.setBounds(280, 190, 20, 20);

        lb31.setBackground(new java.awt.Color(153, 153, 153));
        lb31.setText("  ");
        jPanel4.add(lb31);
        lb31.setBounds(250, 190, 20, 20);

        lb32.setBackground(new java.awt.Color(153, 153, 153));
        lb32.setText("  ");
        jPanel4.add(lb32);
        lb32.setBounds(250, 210, 20, 20);

        lb26.setBackground(new java.awt.Color(153, 153, 153));
        lb26.setText("  ");
        jPanel4.add(lb26);
        lb26.setBounds(270, 130, 20, 20);

        lb29.setBackground(new java.awt.Color(153, 153, 153));
        lb29.setText("  ");
        jPanel4.add(lb29);
        lb29.setBounds(240, 110, 20, 20);

        lb30.setBackground(new java.awt.Color(153, 153, 153));
        lb30.setText("  ");
        jPanel4.add(lb30);
        lb30.setBounds(240, 130, 20, 20);

        lb35.setBackground(new java.awt.Color(153, 153, 153));
        lb35.setText("  ");
        jPanel4.add(lb35);
        lb35.setBounds(210, 190, 20, 20);

        lb36.setBackground(new java.awt.Color(153, 153, 153));
        lb36.setText("  ");
        jPanel4.add(lb36);
        lb36.setBounds(210, 210, 20, 20);

        lb39.setBackground(new java.awt.Color(153, 153, 153));
        lb39.setText("  ");
        jPanel4.add(lb39);
        lb39.setBounds(180, 190, 20, 20);

        lb33.setBackground(new java.awt.Color(153, 153, 153));
        lb33.setText("  ");
        jPanel4.add(lb33);
        lb33.setBounds(210, 110, 20, 20);

        lb34.setBackground(new java.awt.Color(153, 153, 153));
        lb34.setText("  ");
        jPanel4.add(lb34);
        lb34.setBounds(210, 130, 20, 20);

        lb37.setBackground(new java.awt.Color(153, 153, 153));
        lb37.setText("  ");
        jPanel4.add(lb37);
        lb37.setBounds(170, 110, 20, 20);

        lb44.setBackground(new java.awt.Color(153, 153, 153));
        lb44.setText("  ");
        jPanel4.add(lb44);
        lb44.setBounds(150, 210, 20, 20);

        lb43.setBackground(new java.awt.Color(153, 153, 153));
        lb43.setText("  ");
        jPanel4.add(lb43);
        lb43.setBounds(150, 190, 20, 20);

        lb40.setBackground(new java.awt.Color(153, 153, 153));
        lb40.setText("  ");
        jPanel4.add(lb40);
        lb40.setBounds(180, 210, 20, 20);

        lb38.setBackground(new java.awt.Color(153, 153, 153));
        lb38.setText("  ");
        jPanel4.add(lb38);
        lb38.setBounds(170, 130, 20, 20);

        lb41.setBackground(new java.awt.Color(153, 153, 153));
        lb41.setText("  ");
        jPanel4.add(lb41);
        lb41.setBounds(130, 110, 20, 20);

        lb42.setBackground(new java.awt.Color(153, 153, 153));
        lb42.setText("  ");
        jPanel4.add(lb42);
        lb42.setBounds(130, 130, 20, 20);

        lb47.setBackground(new java.awt.Color(153, 153, 153));
        lb47.setText("  ");
        jPanel4.add(lb47);
        lb47.setBounds(110, 190, 20, 20);

        lb48.setBackground(new java.awt.Color(153, 153, 153));
        lb48.setText("  ");
        jPanel4.add(lb48);
        lb48.setBounds(110, 210, 20, 20);

        lb50.setBackground(new java.awt.Color(153, 153, 153));
        lb50.setText("  ");
        jPanel4.add(lb50);
        lb50.setBounds(60, 130, 20, 20);

        lb45.setBackground(new java.awt.Color(153, 153, 153));
        lb45.setText("  ");
        jPanel4.add(lb45);
        lb45.setBounds(100, 110, 20, 20);

        lb46.setBackground(new java.awt.Color(153, 153, 153));
        lb46.setText("  ");
        jPanel4.add(lb46);
        lb46.setBounds(100, 130, 20, 20);

        lb49.setBackground(new java.awt.Color(153, 153, 153));
        lb49.setText("  ");
        jPanel4.add(lb49);
        lb49.setBounds(60, 110, 20, 20);

        jLabel2.setBackground(new java.awt.Color(255, 0, 102));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/busFondo.png"))); // NOI18N
        jPanel4.add(jLabel2);
        jLabel2.setBounds(20, 70, 620, 210);

        jLabelPorcentajeO.setBackground(new java.awt.Color(0, 0, 0));
        jLabelPorcentajeO.setFont(new java.awt.Font("Tahoma", 0, 50)); // NOI18N
        jLabelPorcentajeO.setText("       0 %");
        jPanel4.add(jLabelPorcentajeO);
        jLabelPorcentajeO.setBounds(430, 240, 240, 170);

        jtpBus.addTab("Bus", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtpBus))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtpBus)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        if((Integer.parseInt(jBoxSilla.getSelectedItem().toString())==1)||(Integer.parseInt(jBoxSilla.getSelectedItem().toString())<=4)||
                (Integer.parseInt(jBoxSilla.getSelectedItem().toString())==47)||Integer.parseInt(jBoxSilla.getSelectedItem().toString())==48){
            JOptionPane.showMessageDialog(this, "SILLAS RESERVADAS PARA NECESIDADES DEL VIAJE");
        }else{
            String Nombre = txtNombre.getText();
            String Cedula = txtCedula.getText();
            System.out.println(Nombre);
            System.out.println(Cedula);
            int Numero = Integer.parseInt((String) jBoxSilla.getSelectedItem());
            Pasajero pasajero = new Pasajero();
            pasajero.setNombre(Nombre);
            pasajero.setCedula(Cedula);
            buSillas.getSilla()[Numero-1].setDisponibilidad(false);
            buSillas.getSilla()[Numero - 1].setPasajero(pasajero);
            System.out.println(buSillas);
            System.out.println(pasajero);
            txtNombre.setText("");
            txtCedula.setText("");
            jBoxClase.setSelectedIndex(0);
            jBoxPosicion.removeAllItems();
            jBoxSilla.removeAllItems();
            String PorDisponible = String.valueOf((Ocupacion() * 100) / 50) + "%";
            jLabelPorcentajeO.setText(PorDisponible);
            jLabelPrecio.setText("0$");
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void jBoxPosicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBoxPosicionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBoxPosicionActionPerformed

    private void jBoxPosicionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jBoxPosicionItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            this.jBoxSilla.setModel(new DefaultComboBoxModel(this.getSillas((this.jBoxClase.getSelectedItem().toString()),
                this.jBoxPosicion.getSelectedItem().toString())));
    }
    }//GEN-LAST:event_jBoxPosicionItemStateChanged

    private void jBoxSillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBoxSillaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBoxSillaActionPerformed

    private void jBoxSillaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jBoxSillaItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            int p = Integer.parseInt(this.jBoxSilla.getSelectedItem().toString());
            int precio = buSillas.getSilla()[p - 1].getPrecio();
            this.jLabelPrecio.setText(String.valueOf(precio));
        }
    }//GEN-LAST:event_jBoxSillaItemStateChanged

    private void jBoxClaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBoxClaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBoxClaseActionPerformed

    private void jBoxClaseItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jBoxClaseItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            this.jBoxPosicion.setModel(new DefaultComboBoxModel(this.getPosicion(this.jBoxClase.getSelectedItem().toString())));
        }
    }//GEN-LAST:event_jBoxClaseItemStateChanged

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        Menu btnAtras = new Menu();
        btnAtras.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        String cedula = JOptionPane.showInputDialog(this, "Ingrese el NIT");
        boolean bandera=false;
        Pasajero objPasajero2 = new Pasajero();
        Pasajero[] buscarPasajero = objPasajero2.getObjPasajero();
        for (int i = 0; i < buscarPasajero.length; i++) {
            if (buscarPasajero[i].getCedulaPersona().equals(cedula)) {
                txtNombre.setText(buscarPasajero[i].getNombrePersona());
                txtCedula.setText(buscarPasajero[i].getCedulaPersona());
                lbEscogerBus.setEnabled(true);
                cbBus.setEnabled(true);
                bandera=true;
                System.out.println("cantidad sillas gui "+cantidadSillas);
                
                
                break;
            }
        }
        if(!bandera){
            JOptionPane.showMessageDialog(this, "Cliente no Encontrado");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void cbBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbBusActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaActionPerformed
    public void obtenerBus(){
        
        for(int i=0; i<vectorBuses.length;i++){
            if(vectorBuses[i]!=null){
                cbBus.addItem(vectorBuses[i].getPlaca());
                pos=i;
            }
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReservaGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReservaGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReservaGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReservaGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReservaGui().setVisible(true);
            }
        });
    }
    public int Ocupacion() {
        int CuentaSillascupadas = 0;
        for (int i = 0; i < 50; i++) {
            if ((buSillas.getSilla()[i].isDisponibilidad() == false)||(i==0)||(i<4)||(i==47)||(i==48)) {
                puesto[i].setBackground(Color.RED);
                CuentaSillascupadas++;
                System.out.println("puesto "+i+"Cuenta sillas "+CuentaSillascupadas);
            } else {
                puesto[i].setBackground(Color.CYAN);
            }
        }
        return CuentaSillascupadas;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cbBus;
    private javax.swing.JComboBox<String> jBoxClase;
    private javax.swing.JComboBox<String> jBoxPosicion;
    private javax.swing.JComboBox<String> jBoxSilla;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelPorcentajeO;
    private javax.swing.JLabel jLabelPrecio;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jpReserva;
    private javax.swing.JTabbedPane jtpBus;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label lb1;
    private java.awt.Label lb10;
    private java.awt.Label lb11;
    private java.awt.Label lb12;
    private java.awt.Label lb13;
    private java.awt.Label lb14;
    private java.awt.Label lb15;
    private java.awt.Label lb16;
    private java.awt.Label lb17;
    private java.awt.Label lb18;
    private java.awt.Label lb19;
    private java.awt.Label lb2;
    private java.awt.Label lb20;
    private java.awt.Label lb21;
    private java.awt.Label lb22;
    private java.awt.Label lb23;
    private java.awt.Label lb24;
    private java.awt.Label lb25;
    private java.awt.Label lb26;
    private java.awt.Label lb27;
    private java.awt.Label lb28;
    private java.awt.Label lb29;
    private java.awt.Label lb3;
    private java.awt.Label lb30;
    private java.awt.Label lb31;
    private java.awt.Label lb32;
    private java.awt.Label lb33;
    private java.awt.Label lb34;
    private java.awt.Label lb35;
    private java.awt.Label lb36;
    private java.awt.Label lb37;
    private java.awt.Label lb38;
    private java.awt.Label lb39;
    private java.awt.Label lb4;
    private java.awt.Label lb40;
    private java.awt.Label lb41;
    private java.awt.Label lb42;
    private java.awt.Label lb43;
    private java.awt.Label lb44;
    private java.awt.Label lb45;
    private java.awt.Label lb46;
    private java.awt.Label lb47;
    private java.awt.Label lb48;
    private java.awt.Label lb49;
    private java.awt.Label lb5;
    private java.awt.Label lb50;
    private java.awt.Label lb6;
    private java.awt.Label lb7;
    private java.awt.Label lb8;
    private java.awt.Label lb9;
    private javax.swing.JLabel lbEscogerBus;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
